
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'citi_bike'
version: '1.0.0'
config-version: 2

vars:
  min_date: "1900-01-01 00:00:00"
  max_date: "9999-12-31 00:00:00"

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  citi_bike:
    marts:
      +database: WH_Gold_RAB
      +materialized: table
      +docs:
        node_color: "#132a13"
        
    intermediate:
      +database: WH_Silver_Tech_One
      +materialized: view
      +docs:
        node_color: "#004b23"

    staging:
      +database: WH_Silver_Tech_One
      +materialized: view
      +docs:
        node_color: "#008000"

  dbt_project_evaluator:
    +database: WH_dbt_Project_Evaluator

    
snapshots:
  citi_bike:
    +target_database: WH_Silver_Tech_One
    +dbt_valid_to_current: "to_date('9999-12-31')"
    +docs:
      node_color: "#006400"
    

seeds:
  citi_bike:
    dbt_project_evaluator_seeds:
      +database: WH_dbt_Project_Evaluator
      
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false



# dbt_project_evaluator macro to test project's development quality
dispatch:
  - macro_namespace: dbt
    search_order: ['dbt_project_evaluator', 'dbt']
