USE ROLE DEV_ROLE_TRANSFORMATION;
USE DATABASE STG_DW;
SELECT 'DROP TABLE IF EXISTS ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ';' AS CODE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'INFORMATION_SCHEMA', 'PUBLIC')
AND TABLE_CATALOG IN ('STG_DW')
AND TABLE_SCHEMA LIKE 'DEV%'
AND TABLE_TYPE = 'BASE TABLE'
UNION
SELECT 'DROP VIEW IF EXISTS ' || TABLE_CATALOG || '.' || TABLE_SCHEMA || '.' || TABLE_NAME || ';' AS CODE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_CATALOG NOT IN ('SNOWFLAKE', 'INFORMATION_SCHEMA', 'PUBLIC')
AND TABLE_CATALOG IN ('STG_DW')
AND TABLE_SCHEMA LIKE 'DEV%'
AND TABLE_TYPE = 'VIEW';