USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

ALTER ACCOUNT SET TIMEZONE = 'Pacific/Auckland';

--------------------------------------------------------------------------
--Roles
--------------------------------------------------------------------------

CREATE OR REPLACE ROLE ROLE_INGESTION;
GRANT ROLE ROLE_INGESTION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_INGESTION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE ROLE_INGESTION;

CREATE OR REPLACE ROLE DEV_ROLE_TRANSFORMATION;
GRANT ROLE DEV_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE DEV_ROLE_TRANSFORMATION;

CREATE OR REPLACE ROLE TEST_ROLE_TRANSFORMATION;
GRANT ROLE TEST_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE TEST_ROLE_TRANSFORMATION;

CREATE OR REPLACE ROLE PROD_ROLE_TRANSFORMATION;
GRANT ROLE PROD_ROLE_TRANSFORMATION TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE PROD_ROLE_TRANSFORMATION;


CREATE OR REPLACE ROLE PROD_ROLE_REPORT;
GRANT ROLE PROD_ROLE_REPORT TO ROLE SYSADMIN;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE PROD_ROLE_REPORT;

--------------------------------------------------------------------------
--Databases
--------------------------------------------------------------------------


USE ROLE ROLE_INGESTION;
CREATE OR REPLACE DATABASE RAW;
CREATE OR REPLACE SCHEMA CITI_BIKE;

GRANT USAGE ON DATABASE RAW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE RAW TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT USAGE ON SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT SELECT ON ALL TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SECURITYADMIN; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW.CITI_BIKE TO ROLE PROD_ROLE_TRANSFORMATION;

USE ROLE SYSADMIN;
CREATE OR REPLACE DATABASE STG_DATASTORE;
CREATE SCHEMA STG_DATASTORE.TEST;
CREATE SCHEMA STG_DATASTORE.PROD;

CREATE OR REPLACE DATABASE DATASTORE;
CREATE SCHEMA DATASTORE.TEST;
CREATE SCHEMA DATASTORE.PROD;

CREATE OR REPLACE DATABASE STG_DW;
CREATE SCHEMA STG_DW.TEST;
CREATE SCHEMA STG_DW.PROD;

CREATE OR REPLACE DATABASE DW;
CREATE SCHEMA DW.TEST;
CREATE SCHEMA DW.PROD;

CREATE OR REPLACE DATABASE DBT_PROJECT_EVALUATOR;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.TEST;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.PROD;

GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DATASTORE TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DATASTORE TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DATASTORE TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DATASTORE TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE STG_DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE STG_DW TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT USAGE ON DATABASE DW TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DW TO ROLE PROD_ROLE_REPORT;

GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT USAGE ON DATABASE DBT_PROJECT_EVALUATOR TO ROLE PROD_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.TEST TO ROLE TEST_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.TEST TO ROLE TEST_ROLE_TRANSFORMATION;

GRANT ALL ON SCHEMA STG_DATASTORE.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.PROD TO ROLE PROD_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.PROD TO ROLE PROD_ROLE_TRANSFORMATION;


GRANT USAGE ON SCHEMA DW.PROD TO ROLE PROD_ROLE_REPORT;

USE ROLE SECURITYADMIN; 
GRANT SELECT ON FUTURE TABLES IN SCHEMA DW.PROD TO ROLE PROD_ROLE_REPORT;


--------------------------------------------------------------------------
--dbt-specifc user
--------------------------------------------------------------------------

USE ROLE SYSADMIN;
CREATE SCHEMA STG_DATASTORE.DBT_CCOELHO;
CREATE SCHEMA DATASTORE.DBT_CCOELHO;
CREATE SCHEMA STG_DW.DBT_CCOELHO;
CREATE SCHEMA DW.DBT_CCOELHO;
CREATE SCHEMA DBT_PROJECT_EVALUATOR.DBT_CCOELHO;

GRANT ALL ON SCHEMA STG_DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DATASTORE.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA STG_DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DW.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;
GRANT ALL ON SCHEMA DBT_PROJECT_EVALUATOR.DBT_CCOELHO TO ROLE DEV_ROLE_TRANSFORMATION;



--------------------------------------------------------------------------
--Stages and File Formats
--------------------------------------------------------------------------

USE ROLE ROLE_INGESTION;
CREATE OR REPLACE STAGE RAW.CITI_BIKE.AZURE_CITI_BIKE
URL = 'azure://CHANGE-ME.blob.core.windows.net/citi-bike/data/'
CREDENTIALS = (
    AZURE_SAS_TOKEN = 'sp=CHANGE-ME-nPI9js8%3D');

CREATE OR REPLACE STAGE RAW.CITI_BIKE.S3_NYC_WEATHER
url = 's3://snowflake-workshop-lab/weather-nyc';

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_CSV_01
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null')
    EMPTY_FIELD_AS_NULL = true
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE;

CREATE OR REPLACE FILE FORMAT RAW.CITI_BIKE.FF_JSON_01
    TYPE = 'JSON';


--------------------------------------------------------------------------
--Create Tables
--------------------------------------------------------------------------
    

CREATE OR REPLACE TABLE RAW.CITI_BIKE.TRIPS (
	TRIPDURATION NUMBER(38,0),
	STARTTIME TIMESTAMP_NTZ(9),
	STOPTIME TIMESTAMP_NTZ(9),
	START_STATION_ID NUMBER(38,0),
    START_STATION_NAME STRING,
    START_STATION_LATITUDE FLOAT,
    START_STATION_LONGITUDE FLOAT,
	END_STATION_ID NUMBER(38,0),
    END_STATION_NAME STRING,
    END_STATION_LATITUDE FLOAT,
    END_STATION_LONGITUDE FLOAT,
	BIKEID NUMBER(38,0),
	USERTYPE STRING,
	BIRTH_YEAR NUMBER(38,0),
	GENDER NUMBER(38,0), 
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.CITI_BIKE.WEATHER_NYC (
	DATA VARIANT,
    METADATA_FILENAME STRING, 
    METADATA_FILE_ROW_NUMBER INT, 
    METADATA_FILE_LAST_MODIFIED TIMESTAMP
);


--------------------------------------------------------------------------
--Ingest data
--------------------------------------------------------------------------

USE ROLE ROLE_INGESTION;
COPY INTO RAW.CITI_BIKE.TRIPS from (
    SELECT 
        $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
        ,METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @RAW.CITI_BIKE.AZURE_CITI_BIKE
    (FILE_FORMAT => 'RAW.CITI_BIKE.FF_CSV_01', PATTERN => '.*trips*.*csv.*')
);


COPY INTO RAW.CITI_BIKE.WEATHER_NYC from (
    SELECT 
        $1
        ,METADATA$FILENAME, METADATA$FILE_ROW_NUMBER, METADATA$FILE_LAST_MODIFIED
    FROM @RAW.CITI_BIKE.S3_NYC_WEATHER
    (FILE_FORMAT => 'RAW.CITI_BIKE.FF_JSON_01', PATTERN => '.*weather*.*json.*')
);


--------------------------------------------------------------------------
--END
--------------------------------------------------------------------------
